apiVersion: v1
kind: Service
metadata:
  name: first-pipeline-service
spec:
  selector:
    app: first-pipeline
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31701
  type: NodePort
